### ISSUE TITLE
GCP projects stuck in Cleaning block other projects from cleaning

### ISSUE THREAD

**Issue by chemikadze** [kubernetes-sigs/boskos#112]
As far as I understood [this logic](https://github.com/kubernetes-sigs/boskos/blob/master/cmd/janitor/janitor.go#L127) correctly, Janitor tries to acquire and clean all dirty resources sequentially, type by type; acquisition is also throttled by size of the channel. If cleaning fails, janitor returns resource back to dirty state, and if acquisition was throttled, loop will try to get same resource again. So if janitor(s) are putting resources back to dirty fast enough, it's possible for janitor to get stuck on one resource type and do nothing for other resource types.

This was observed previously with [filestore](https://github.com/kubernetes-sigs/boskos/pull/111) cleans in private install: multiple resource types have been affected after one of types got more projects stuck in cleaning than aggregated capacity of channels in all janitor instances.

**Comment by chizhg** [comment]
Two questions about this:
1. Is it possible to fix the firestore cleanup?
2. Have you tried adding more replicas for the Janitor deployment? For us we usually set the number of it as ~1/16 of the total number of projects, and it has been working fine even when there are occasionally clean-up failures.

**Comment by chemikadze** [comment]
> Is it possible to fix the firestore cleanup?

Yes, that was fixed by #111

> Have you tried adding more replicas for the Janitor deployment? For us we usually set the number of it as ~1/16 of the total number of projects, and it has been working fine even when there are occasionally clean-up failures.

This particular problem happens if cleanup failures are irrecoverable, and number of projects stuck in cleanup exceeds aggregate number of threads that all replicas of janitor run. In that case one specific resource type can cause entire janitor deployment to get stuck, impacting other resource types.

This issue is basically a followup from #111 - similar issues happening in future in particular resource type should not be impacting other resource types.
