### ISSUE TITLE
Boskos client does not distinguish between incorrect resource type and no resources available

### ISSUE THREAD

**Issue by bartekmi** [kubernetes-sigs/boskos#126]
Currently, when acquiring a resource using AcquireWait(), the client makes no distinction between a resource type that does not exist (which could arise from a user typo) vs. a situation where all resources are busy. 

Unfortunately, the Boskos Server sends the 404 status code in both situation - [see code here](https://github.com/kubernetes-sigs/boskos/blob/9fae38623263fd9251734b5dd5d78a0f09c3876a/handlers/handlers.go#L71). The Boskos client then looks at the status code [here](https://github.com/kubernetes-sigs/boskos/blob/d007e4465eb6fcc4ab275698353fe3bafbeb28d5/client/client.go#L191).

One easy and backwards-compatible fix would be to add a new option to the client that, when set, would distinguish between the two situation based on the text returned from the HTTP call. The return text for the two different situations is:

- Acquire failed: resource type "my-resource-type" does not exist
- Acquire failed: no available resource my-resource-type, try again later

The current problem is that if the user accidentally asks for a resource type that does not exist, they will be stuck in a loop forever with no hope of unblocking except for a Context timeout, which, imo, is not an acceptable situation.

**Comment by chaodaiG** [comment]
this sounds reasonable to me
