### ISSUE TITLE
Updates silently fail if configuration file is renamed

### ISSUE THREAD

**Issue by ixdy** [kubernetes-sigs/boskos#42]
Boskos *should* fail on startup if the path to the config file is invalid.

We've discovered a deployment where Boskos is not updating its configuration.

What I think happened is that the `--config` flag pointed to a valid configuration file, and then at some point, the filename inside ConfigMap changed, resulting in the original file being deleted.

It appears that viper [simply silently stops its file watch](https://github.com/spf13/viper/blob/master/viper.go#L389) when a file is deleted, so there's no good way to detect if this error has occurred until the pod restarts.

I don't have a good idea for how to resolve this - should we periodically check the config file and crash if it's no longer valid? That'd also help a bit with https://github.com/kubernetes-sigs/boskos/issues/20. (If we didn't crash, we'd at least get error messages that might be helpful for users trying to figure out why their configs aren't being updated.)

cc @coryrc

**Comment by ixdy** [comment]
I wonder if this is still an issue after https://github.com/kubernetes-sigs/boskos/pull/54.

cc @alvaroaleman

**Comment by alvaroaleman** [comment]
No, should result in an error log:
* Fsnotify trigger: https://github.com/kubernetes-sigs/boskos/pull/54/files#diff-db5d492b9d936985cebe6decf1333cb7e85f6058c584c683a8dafcb58b9c4b65R153
* Error log if sync fails: https://github.com/kubernetes-sigs/boskos/pull/54/files#diff-db5d492b9d936985cebe6decf1333cb7e85f6058c584c683a8dafcb58b9c4b65R183

**Comment by ixdy** [comment]
hm, but I think viper still won't call that fsnotify trigger if the config file is deleted (per https://github.com/spf13/viper/blob/d10c856f6c7be1fcdfc692b912e1d047c3ac0036/viper.go#L389)

**Comment by ixdy** [comment]
though I guess it'll try to sync (and then log errors) whenever a resource is set to an empty owner, which is better than nothing.
