### ISSUE TITLE
Bazel build error: Fake packages must not be imported in non-fake package

### ISSUE THREAD

**Issue by chizhg** [kubernetes-sigs/boskos#53]
Below error is from the build log when building with `bazel`:

`fake package sigs.k8s.io/controller-runtime/pkg/client/fake must not be imported in non-fake package sigs.k8s.io/boskos/crds`

**Comment by ixdy** [comment]
Is this error coming from nogo? If so, you can add an exception for boskos.

(I think these imports are only in test files. We could probably change these to be external tests, but a bit of refactoring would be necessary.)
