### ISSUE TITLE
aws-janitor: ensure IDs are unique across resources and regions for set.Mark

### ISSUE THREAD

**Issue by ixdy** [kubernetes-sigs/boskos#55]
Some AWS resources don't have an ARN, so we're currently just using the ID of the resource, which may not necessarily be globally unique for the same resource and/or across resource types.

For several resource types, we generate a fake ARN which includes the resource type and region. We should ensure all resource types are doing something similar.

/kind cleanup

**Comment by cpanato** [comment]
hello @ixdy 
I would like to contribute to this, can you point to me one example where this is generated for a resource?
thanks!

**Comment by ixdy** [comment]
Yep, that's a perfect example. Thanks!

/assign @cpanato

**Comment by cpanato** [comment]
@ixdy thanks! i will work on that
