### ISSUE TITLE
Release boskosctl :)

### ISSUE THREAD

**Issue by cpanato** [kubernetes-sigs/boskos#73]
will be good to make a release of boskosctl

/cc @ixdy @alvaroaleman

**Comment by alvaroaleman** [comment]
We already do, there is e.G. `gcr.io/k8s-staging-boskos/boskosctl:v20210209-abc8061`

**Comment by cpanato** [comment]
@alvaroaleman thanks!

it is supposed just to use the image? I was thinking to have the binary for Linux/mac

**Comment by alvaroaleman** [comment]
I suppose you could also `go get` it or something, but the image has IMHO the advantage that it includes a version number and can be used in jobs

**Comment by ixdy** [comment]
I'm not opposed to there being binary releases of the CLI, but we don't have any real process for that as of now.

Somewhat tangentially, eventually I'd like to actually tag "official" releases and promote them from `gcr.io/k8s-staging-boskos` to `k8s.gcr.io`, but that has thus far been a fairly low priority.

**Comment by cpanato** [comment]
not a problem, just wondering thanks for the feedback

I will close this
/close
