### ISSUE TITLE
Deleting static resource may not take effect until next config update or container restart

### ISSUE THREAD

**Issue by chemikadze** [kubernetes-sigs/boskos#83]
Static resources are deleted only on "SyncConfig", which is triggered by config map update, and in-use resource deletion is delayed until next SyncConfig. But sync happens only on container restart or config change - so if resource was in use, deletion may be significantly delayed.

Dynamic resources however are updated at same time as static + on dynamic-resource-update-period (10 minutes by default). Should static resources be updated as well with similar cadence?

**Comment by ixdy** [comment]
This sounds similar to #20, which I think was fixed by #54 (back in ~December 2020). What build of Boskos are you using?
